### ISSUE TITLE
linux 版本何时发布？

### ISSUE THREAD

**Issue by pureGavin** [MinerProxy/MinerProxy#1]
linux 版本何时发布？

**Comment by wisebuilder** [comment]
The linux version is my own development prototype. In the end, all the functions in linux will be implemented in windows. After windows is completely perfected, I will find time to release the linux version. After all, most miners are not too familiar with Linux.

**Comment by pureGavin** [comment]
> The linux version is my own development prototype. In the end, all the functions in linux will be implemented in windows. After windows is completely perfected, I will find time to release the linux version. After all, most miners are not too familiar with Linux.

我不是很明白你的矿池代理的工作原理，如果在一台Windows上开矿池代理，别的矿机都连接到这台Windows，那么流量走的就都是这台Windows，如果这台Windows机器在中国大陆的话，这个代理有什么意义呢？

**Comment by Error996** [comment]
可以用 https://github.com/HyNetwork/hysteria 进行双边加速 tcp转发，做这个代理的上级，能有效避免各种你想的问题

**Comment by wisebuilder** [comment]
> > The linux version is my own development prototype. In the end, all the functions in linux will be implemented in windows. After windows is completely perfected, I will find time to release the linux version. After all, most miners are not too familiar with Linux.
> 
> 我不是很明白你的矿池代理的工作原理，如果在一台Windows上开矿池代理，别的矿机都连接到这台Windows，那么流量走的就都是这台Windows，如果这台Windows机器在中国大陆的话，这个代理有什么意义呢？

本地装MP的好处是：
1、可以集中管理矿机，比如更改矿池，统一钱包，做到瞬间切换，不必去每台矿机进行更改
2、有些矿机不能直接ssl进行矿池连接，可以连接到本地MP然后统一连接SSL矿池
3、可以让本地矿机不必联网，只在MP这台机器进行外网连接即可，这样可以通过透明代理方便出海连接矿池
4、更大的好处是（下个版本提供），本地MP会建立矿池池（4路：主矿池、备份矿池各两路，提供stratum和proxy方式连接），用最少的流量和矿池进行连接，为本地矿机提供工作和工作共享提交
5、（此点目前正在开发测试中）如果通过在境外VPS上安装MP，则可以通过本地MP与vps上的MP进行KCP协议方式通讯保证最少的流量和最快最稳定的速度接收工作和提交共享，且MP之间通过加密数据传输保证了数据安全性和不被检测。

**Comment by pureGavin** [comment]
> 可以用 https://github.com/HyNetwork/hysteria 进行双边加速 tcp转发，做这个代理的上级，能有效避免各种你想的问题

感谢分享，但是我看介绍说是代理程序，如果真的仅仅只是代理的话，直接用V2ray的SOCK5代理不行么？

**Comment by pureGavin** [comment]
> > > The linux version is my own development prototype. In the end, all the functions in linux will be implemented in windows. After windows is completely perfected, I will find time to release the linux version. After all, most miners are not too familiar with Linux.
> > 
> > 
> > 我不是很明白你的矿池代理的工作原理，如果在一台Windows上开矿池代理，别的矿机都连接到这台Windows，那么流量走的就都是这台Windows，如果这台Windows机器在中国大陆的话，这个代理有什么意义呢？
> 
> 本地装MP的好处是： 1、可以集中管理矿机，比如更改矿池，统一钱包，做到瞬间切换，不必去每台矿机进行更改 2、有些矿机不能直接ssl进行矿池连接，可以连接到本地MP然后统一连接SSL矿池 3、可以让本地矿机不必联网，只在MP这台机器进行外网连接即可，这样可以通过透明代理方便出海连接矿池 4、更大的好处是（下个版本提供），本地MP会建立矿池池（4路：主矿池、备份矿池各两路，提供stratum和proxy方式连接），用最少的流量和矿池进行连接，为本地矿机提供工作和工作共享提交 5、（此点目前正在开发测试中）如果通过在境外VPS上安装MP，则可以通过本地MP与vps上的MP进行KCP协议方式通讯保证最少的流量和最快最稳定的速度接收工作和提交共享，且MP之间通过加密数据传输保证了数据安全性和不被检测。

好处确实很多，但是针对中国大陆的好处可能就是第四和第五点了，关于第五点在VPS上安装MP确实有用，但是最大的问题是Windows系统的VPS每个月需要多给一些钱，而Linux的VPS，系统是免费使用的，所以我还是更倾向于VPS版本的MP要做Linux的

**Comment by Error996** [comment]
不是代理，他有个tcp转发～直接转发矿池端口就行，本地弄个单独的机器跑客户端，出一个tcp端口，矿机都连局域网端口相当于连接矿池，且中间全部数据没有任何特征

**Comment by Error996** [comment]
> > > The linux version is my own development prototype. In the end, all the functions in linux will be implemented in windows. After windows is completely perfected, I will find time to release the linux version. After all, most miners are not too familiar with Linux.
> > 
> > 
> > 我不是很明白你的矿池代理的工作原理，如果在一台Windows上开矿池代理，别的矿机都连接到这台Windows，那么流量走的就都是这台Windows，如果这台Windows机器在中国大陆的话，这个代理有什么意义呢？
> 
> 本地装MP的好处是： 1、可以集中管理矿机，比如更改矿池，统一钱包，做到瞬间切换，不必去每台矿机进行更改 2、有些矿机不能直接ssl进行矿池连接，可以连接到本地MP然后统一连接SSL矿池 3、可以让本地矿机不必联网，只在MP这台机器进行外网连接即可，这样可以通过透明代理方便出海连接矿池 4、更大的好处是（下个版本提供），本地MP会建立矿池池（4路：主矿池、备份矿池各两路，提供stratum和proxy方式连接），用最少的流量和矿池进行连接，为本地矿机提供工作和工作共享提交 5、（此点目前正在开发测试中）如果通过在境外VPS上安装MP，则可以通过本地MP与vps上的MP进行KCP协议方式通讯保证最少的流量和最快最稳定的速度接收工作和提交共享，且MP之间通过加密数据传输保证了数据安全性和不被检测。

KCP不行，gfw的ai训练早就识别了，毛用没有，目前唯一解就是wss要不然trojan之类的不会弄个回落到正常网页，挖矿还最怕的就是tcp干扰，随便找个wss的代码拿来就用还能走cdn，敏感时期都不带有问题的～

**Comment by pureGavin** [comment]
> > > > The linux version is my own development prototype. In the end, all the functions in linux will be implemented in windows. After windows is completely perfected, I will find time to release the linux version. After all, most miners are not too familiar with Linux.
> > > 
> > > 
> > > 我不是很明白你的矿池代理的工作原理，如果在一台Windows上开矿池代理，别的矿机都连接到这台Windows，那么流量走的就都是这台Windows，如果这台Windows机器在中国大陆的话，这个代理有什么意义呢？
> > 
> > 
> > 本地装MP的好处是： 1、可以集中管理矿机，比如更改矿池，统一钱包，做到瞬间切换，不必去每台矿机进行更改 2、有些矿机不能直接ssl进行矿池连接，可以连接到本地MP然后统一连接SSL矿池 3、可以让本地矿机不必联网，只在MP这台机器进行外网连接即可，这样可以通过透明代理方便出海连接矿池 4、更大的好处是（下个版本提供），本地MP会建立矿池池（4路：主矿池、备份矿池各两路，提供stratum和proxy方式连接），用最少的流量和矿池进行连接，为本地矿机提供工作和工作共享提交 5、（此点目前正在开发测试中）如果通过在境外VPS上安装MP，则可以通过本地MP与vps上的MP进行KCP协议方式通讯保证最少的流量和最快最稳定的速度接收工作和提交共享，且MP之间通过加密数据传输保证了数据安全性和不被检测。
> 
> KCP不行，gfw的ai训练早就识别了，毛用没有，目前唯一解就是wss要不然trojan之类的不会弄个回落到正常网页，挖矿还最怕的就是tcp干扰，随便找个wss的代码拿来就用还能走cdn，敏感时期都不带有问题的～

我记得V2ray有个能在正常代理包的外层裹一个ping baidu的包，这种我用着也还可以，快两年了也没让GFW检测到，不知道能不能用来当挖矿的代理方法

**Comment by Error996** [comment]
那是上网用的，你用来miner肯定不行的，miner需要高并发短延迟，你这相当于一层套一层～变相增大处理器的解密压力，就是一个不被识别的最简单的协议，不要用复杂处理方式，工作方式就是端口映射，通过加密把远端端口拉到局域网里，这样路由器除了这个客户端的机器其他全部禁止上网
